Basic constants for the AI engine.

REGION_DEFAULT = "IN-DEL"
NDVI_FILL_VALUE = -1.0
RAIN_FILL_VALUE = 0.0
TEMPERATURE_FILL_VALUE = 25.0
SOIL_MOISTURE_FILL_VALUE = 0.0
ALERT_FILL_VALUE = 0
MAX_WINDOW_DAYS = 30
SEED = 42
